### PR TITLE
Ui fixes

### LINKED ISSUE #3: Add Last Modified beside the bug
Display last modified next to status using pretty dates (... ago )

### LINKED ISSUE #7: Color scheme for bugs
White for NEW (and/or UNCONFIRMED?)
Grayed out for ASSIGNED
Greenish (pale/ light) for RESOLVED *

Color should be applied on panel.

### LINKED ISSUE #8: Changes in prize wording
Prefix prize with "Prize:" tag (use tag?) and create tooltip with following text: "If you have fixed this bug before the end of the event, please come by the Mozilla booth to pick up your [prize]"

### PR DESCRIPTION
**Pull request by comzeradd**
- Fixes #8 
- Fixes #7 
- Fixes #3

### CODE REVIEW

**Comment by comzeradd** [comment]
@ppapadeas could you have a look?

**Comment by comzeradd** [comment]
ribbon

**Comment by ppapadeas** [comment]
Nice :) I would suggest to move it on the right-up corner and put the color on the background of the ribbon not the text.

**Comment by comzeradd** [comment]
ribbon

**Pull request merged**
